name: 1.$(Build.BuildId).$(Rev:rr)
pr:
- main
trigger:
- main

resources:
  repositories:
  - repository: ci
    type: git
    name: Impower.Support.Pipelines
    trigger: none
  - repository: impower
    type: github
    name: impower-ai/uipath-ado-templates
    endpoint: GithubConnection
    trigger: none

pool:
   vmImage: windows-latest

stages:
- template: /templates/csharp-build.yaml@impower
  parameters:
    target_resource_name: 'self'
- template: /templates/deploy-template.yml@impower
  parameters:
    stage_name: 'Deploy_Orchestrator'
    orchestrator_folder : 'Shared'
    service_connection: 'UiPath-Development'
    azure_environment: 'Impower-Development'
    stage_dependencies:
    - 'Build'
- template: /templates/publish-to-nuget-feed.yaml@impower
  parameters:
    artifact_directory: 'CSharp Package'
    service_connection: 'ImpowerAiNuget'
    azure_environment: 'NugetOrg'
    stage_name: 'Deploy_Nuget'
    stage_dependencies:
    - 'Build'
